name: Call Claude API

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  call-claude:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Validate API Key
      run: |
        if [ -z "$CLAUDE_API_KEY" ]; then
          echo "Error: API key is not set. Please configure CLAUDE_API_KEY in repository secrets."
          exit 1
        fi

    - name: Call Claude API
      env:
        CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }} # Store API key securely in GitHub Secrets
      run: |
        echo "Calling Claude API..."
        curl --verbose -X POST "https://api.claude.example.com/v1/chat" \
          -H "Authorization: Bearer $CLAUDE_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{
                "input": "Hello, Claude!",
                "parameters": {
                  "temperature": 0.7,
                  "max_tokens": 256
                }
              }' || echo "Error: API call failed"